[project]
name = "trabalho-pratico-grafos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pre-commit>=4.3.0",
    "ruff>=0.14.4",
]
